environment:
  ANDROID_HOME: "C:\\android"

init:
  - mkdir "%ANDROID_HOME%"
  - cd "%ANDROID_HOME%"
  - appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip"
  - 7z x "tools_r25.2.3-windows.zip" > nul
  - cd "C:\projects\libresubstratum"

install: off
build: off

test_script: off
